server.port: 8090 #tomcat 서버 포트 8090으로 설정

spring:
  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 745601749347-dikdf3vcmi4njc8s46quov8aapjl7vbt.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile
    user:
      name: user
      password: 1234
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true # java코드로 짠 sql을
    defer-datasource-initialization: true # data.sql 사용을 위해서 필수적으로 등록
    properties:
      hibernate:
        format_sql: true  # sql문 pretty하게 보여줌
        use_sql_comments: true
    generate-ddl: true   # true, false
    hibernate:
      ddl-auto: create    # create, create-drop, update, validate, none
  sql:
    init:
      mode: always
      # always: embeded db가 아닌 외부 db 사용시 spring boot를 실행할때 마다 data.sql schema.sql import.sql을 항상 실행
      # never: data.sql schema.sql 을 실행하지 않음
      encoding: utf-8

mybatis:
    # mapper.xml
    mapper-locations: mybatis-mapper/**/*.xml
    # camel case
    configuration:
      map-underscore-to-camel-case: true
    # package model
    # xml에 있는 모델 앞의 패키지명을 생략 가능하도록 지원해주는 기능
    type-aliases-package: com.thejoeun.practice1.boilerplate1.model;
jwt:
  secret: 1234